export const appQueryKeys = {
  dashboard: ["dashboard-summary"] as const,
  pets: ["pets"] as const,
  pet: (petId: string) => ["pets", petId] as const,
  petDocuments: (petId: string) => ["pets", petId, "documents"] as const,
  emergencyChain: ["emergency-chain"] as const,
  emergencyContact: (contactId: string) => ["emergency-chain", "contact", contactId] as const,
  checkInConfig: ["check-in-config"] as const,
  checkInStatus: ["check-in-status"] as const,
  checkInEvents: ["check-in-events"] as const,
  escalationHistory: ["escalation-history"] as const,
  notifications: ["notifications"] as const,
  emergencyProfile: (petId: string) => ["emergency-profile", petId] as const,
  emergencyProfileRoot: ["emergency-profile"] as const,
  vapidPublicKey: ["vapid-public-key"] as const,
  pushSubscriptions: ["push-subscriptions"] as const,
};
